version: '3.8'
services:
  app:
    build:
      context: .
    container_name: task-manager
    ports:
        - "8080:8080"
    depends_on:
        - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/task-manager-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
  postgres:
      image: postgres
      container_name: postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=task-manager-db
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data: